version: '3'
services:
  mongo:
    image: 'mongo:4.1.4'
    container_name: mongo
    restart: 'always'
    command:
      - '--logpath'
      - '/var/log/mongodb/mongod.log'
    ports:
      - '27017:27017'
    networks:
      - elevate_net
    volumes:
      - mongo-data:/data/db
      - logs:/var/log/mongodb
  redis:
    image: 'redis:7.0.0'
    container_name: redis
    restart: 'always'
    ports:
      - '6379:6379'
    networks:
      - elevate_net
    logging:
      driver: none
  entity:
    build: './src'
    container_name: entity
    ports:
      - '5001:5001'
    command: ['nodemon', 'app.js']
    environment:
      - MONGODB_URL=mongodb://mongo:27017/elevate-diksha
    env_file:
      - ${unnati_env}
    depends_on:
      - mongo
    networks:
      - elevate_net
      
networks:
  elevate_net:
volumes:
  mongo-data:
  logs:
