version: '3'
services:
  redis:
    image: 'redis:7.0.0'
    restart: 'always'
    expose:
      - '6379'
    networks:
      - elevate_net
    logging:
      driver: json-file
  mongo:
    image: 'mongo:4.1.4'
    container_name: mongo
    restart: 'always'
    command:
      - '--logpath'
      - '/var/log/mongodb/mongod.log'
    ports:
      - '27017:27017'
    networks:
      - elevate_net
    volumes:
      - mongo-data:/data/db
      - logs:/var/log/mongodb
  entity_elevate:
    build: '../'
    volumes:
      - ../src/:/var/src
    ports:
      - '5001:5001'
    command: [ 'nodemon', 'app.js' ]
    environment:
      - REDIS_HOST=redis://redis:6379
      - MONGODB_URL=mongodb://mongo:27017/elevate-diksha
    env_file:
      - integration_test.env
    depends_on:
      - kafka
      - mongo
      - redis
    networks:
      - elevate_net
networks:
  elevate_net:
    external: false
volumes:
  mongo-data:
  logs:
